import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { CreateTodo } from "../component/createTodo";
import Todos from "../component/todos";
import { api } from "../utils/api";

const Home: NextPage = () => {
  const {data}= api.todo.all.useQuery()

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex bg-slate-500 min-h-screen flex-col items-center justify-center">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16">
          <div className="grid grid-cols-1 gap-4 md:gap-8">
            <div className="flex flex-col gap-4 rounded-xl bg-white/10 p-4 text-white">
              <p className="text-xl font-bold"> TODO LIST <span className="ml-12 text-gray-200">{`Total ${data?.length}`}</span> </p>
                <p> </p>
              <Todos />
              <CreateTodo />
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
